### ISSUE TITLE
运行 python test_cnn.py 报错

### ISSUE THREAD

**Issue by tianhm** [linyiLYi/snake-ai#19]
os: ubuntu 18.04
error:
Using seed = 783742036 for testing.
Traceback (most recent call last):
  File "test_cnn.py", line 24, in <module>
    env = SnakeEnv(seed=seed, limit_step=False, silent_mode=False)
  File "/home/tianhm/snake-ai/main/snake_game_custom_wrapper_cnn.py", line 11, in __init__
    self.game = SnakeGame(seed=seed, board_size=board_size, silent_mode=silent_mode)
  File "/home/tianhm/snake-ai/main/snake_game.py", line 30, in __init__
    mixer.init()
pygame.error: dsp: No such audio device

但是 python snake_game.py 可以正常执行。

**Comment by icuxika** [comment]
![屏幕截图 2023-07-02 161834](https://github.com/linyiLYi/snake-ai/assets/43027844/a0dd8533-323f-48cd-9340-dc9cf6af3699)
可以暂时让这部分代码不作用就可以了，我实在WSL2的Ubuntu-22.04中遇到这个问题

**Comment by avselang** [comment]
是不是silent_mode设置一下就行？
