### ISSUE TITLE
2023.10.26 test遇到的问题#bug

### ISSUE THREAD

**Issue by CODESpellCaster001** [linyiLYi/snake-ai#29]
输入命令：
(pytorch) PS E:\ai projection\snake-ai-master\main> python .\snake_game.py
报错：
Traceback (most recent call last):
  File "E:\ai projection\snake-ai-master\main\snake_game.py", line 259, in <module>
    game = SnakeGame(seed=seed, silent_mode=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai projection\snake-ai-master\main\snake_game.py", line 51, in __init__
    self.reset()
  File "E:\ai projection\snake-ai-master\main\snake_game.py", line 60, in reset
    self.food = self._generate_food()
                ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ai projection\snake-ai-master\main\snake_game.py", line 140, in _generate_food
    food = random.sample(self.non_snake, 1)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda\envs\pytorch\Lib\random.py", line 439, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
需要修改的地方：
![image](https://github.com/linyiLYi/snake-ai/assets/145527246/0df1ca01-30d1-4e88-a3a6-5c44adab60a7)
and
![image](https://github.com/linyiLYi/snake-ai/assets/145527246/537eccb1-3c70-453e-a18a-c9738eed18f7)

**Comment by CODESpellCaster001** [comment]
self.non_snake = [(row, col) for row in range(self.board_size) for col in range(self.board_size) if
                          (row, col) not in self.snake]

`self.non_snake.append(self.snake.pop())`
